declare module 'vue' {
  export interface GlobalComponents {
    // 基础组件
    ['u-icon']: typeof import('./comps/icon')['Icon']
    ['u-image']: typeof import('./comps/image')['Image']
    ['u-button']: typeof import('./comps/button')['Button']
    ['u-text']: typeof import('./comps/text')['Text']
    ['u-row']: typeof import('./comps/row')['Row']
    ['u-col']: typeof import('./comps/col')['Col']
    ['u-cell']: typeof import('./comps/cell')['Cell']
    ['u-cell-group']: typeof import('./comps/cellGroup')['CellGroup']
    ['u-badge']: typeof import('./comps/badge')['Badge']
    ['u-tag']: typeof import('./comps/tag')['Tag']
    ['u-loading-icon']: typeof import('./comps/loadingIcon')['LoadingIcon']
    ['u-loading-page']: typeof import('./comps/loadingPage')['LoadingPage']

    // 表单组件
    ['u-form']: typeof import('./comps/form')['Form']
    ['u-form-item']: typeof import('./comps/formItem')['FormItem']
    ['u-calendar']: typeof import('./comps/calendar')['Calendar']
    ['u-keyboard']: typeof import('./comps/keyboard')['Keyboard']
    ['u-picker']: typeof import('./comps/picker')['Picker']
    ['u-datetime-picker']: typeof import('./comps/datetimePicker')['DatetimePicker']
    ['u-rate']: typeof import('./comps/rate')['Rate']
    ['u-search']: typeof import('./comps/search')['Search']
    ['u-number-box']: typeof import('./comps/numberBox')['NumberBox']
    ['u-upload']: typeof import('./comps/upload')['Upload']
    ['u-code']: typeof import('./comps/code')['Code']
    ['u-input']: typeof import('./comps/input')['Input']
    ['u-textarea']: typeof import('./comps/textarea')['Textarea']
    ['u-checkbox']: typeof import('./comps/checkbox')['Checkbox']
    ['u-checkbox-group']: typeof import('./comps/checkboxGroup')['CheckboxGroup']
    ['u-radio']: typeof import('./comps/radio')['Radio']
    ['u-radio-group']: typeof import('./comps/radioGroup')['RadioGroup']
    ['u-switch']: typeof import('./comps/switch')['Switch']
    ['u-slider']: typeof import('./comps/slider')['Slider']
    ['u-album']: typeof import('./comps/album')['Album']

    // 数据组件
    ['u-list']: typeof import('./comps/list')['List']
    ['u-list-item']: typeof import('./comps/listItem')['ListItem']
    ['u-line-progress']: typeof import('./comps/lineProgress')['LineProgress']
    ['u-count-down']: typeof import('./comps/countDown')['CountDown']
    ['u-count-to']: typeof import('./comps/countTo')['CountTo']

    // 反馈组件
    ['u-tooltip']: typeof import('./comps/tooltip')['Tooltip']
    ['u-action-sheet']: typeof import('./comps/actionSheet')['ActionSheet']
    ['u-alert']: typeof import('./comps/alert')['Alert']
    ['u-toast']: typeof import('./comps/toast')['Toast']
    ['u-notice-bar']: typeof import('./comps/noticeBar')['NoticeBar']
    ['u-notify']: typeof import('./comps/notify')['Notify']
    ['u-swipe-action']: typeof import('./comps/swipeAction')['SwipeAction']
    ['u-swipe-action-item']: typeof import('./comps/swipeActionItem')['SwipeActionItem']
    ['u-collapse']: typeof import('./comps/collapse')['Collapse']
    ['u-collapse-item']: typeof import('./comps/collapseItem')['CollapseItem']
    ['u-popup']: typeof import('./comps/popup')['Popup']
    ['u-modal']: typeof import('./comps/modal')['Modal']

    // 布局组件
    ['u-scroll-list']: typeof import('./comps/scrollList')['ScrollList']
    ['u-line']: typeof import('./comps/line')['Line']
    ['u-overlay']: typeof import('./comps/overlay')['Overlay']
    ['u-no-network']: typeof import('./comps/noNetwork')['NoNetwork']
    ['u-grid']: typeof import('./comps/grid')['Grid']
    ['u-grid-item']: typeof import('./comps/gridItem')['GridItem']
    ['u-swiper']: typeof import('./comps/swiper')['Swiper']
    ['u-skeleton']: typeof import('./comps/skeleton')['Skeleton']
    ['u-sticky']: typeof import('./comps/sticky')['Sticky']
    ['u-divider']: typeof import('./comps/divider')['Divider']

    // 导航组件
    ['u-tabbar']: typeof import('./comps/tabbar')['Tabbar']
    ['u-tabbar-item']: typeof import('./comps/tabbarItem')['TabbarItem']
    ['u-back-top']: typeof import('./comps/backTop')['BackTop']
    ['u-navbar']: typeof import('./comps/navbar')['Navbar']
    ['u-tabs']: typeof import('./comps/tabs')['Tabs']
    ['u-subsection']: typeof import('./comps/subsection')['Subsection']
    ['u-index-list']: typeof import('./comps/indexList')['IndexList']
    ['u-index-item']: typeof import('./comps/indexItem')['IndexItem']
    ['u-index-anchor']: typeof import('./comps/indexAnchor')['IndexAnchor']
    ['u-steps']: typeof import('./comps/steps')['Steps']
    ['u-steps-item']: typeof import('./comps/stepsItem')['StepsItem']
    ['u-empty']: typeof import('./comps/empty')['Empty']

    // 其他组件
    ['u-parse']: typeof import('./comps/parse')['Parse']
    ['u-code-input']: typeof import('./comps/codeInput')['CodeInput']
    ['u-loadmore']: typeof import('./comps/loadMore')['LoadMore']
    ['u-read-more']: typeof import('./comps/readMore')['ReadMore']
    ['u-gap']: typeof import('./comps/gap')['Gap']
    ['u-avatar']: typeof import('./comps/avatar')['Avatar']
    ['u-avatar-group']: typeof import('./comps/avatarGroup')['AvatarGroup']
    ['u-link']: typeof import('./comps/link')['Link']
    ['u-transition']: typeof import('./comps/transition')['Transition']
    ['u-status-bar']: typeof import('./comps/statusBar')['StatusBar']
    ['u-safe-bottom']: typeof import('./comps/safeBottom')['SafeBottom']
    ['u-qrcode']: typeof import('./comps/qrcode')['Qrcode']
  }
}

export {}
